project 'VirtualCrit3.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VirtualCrit3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iVirtualCrit
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Mapbox-iOS-SDK', '~> 4.8'

end
