project 'VirtualCrit IOS.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'VirtualCrit IOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VirtualCrit IOS

pod 'Firebase'
pod 'Firebase/Database'


end
